import {
  FontAwesome6,
  Ionicons,
  MaterialIcons,
  Entypo,
} from "@expo/vector-icons";

export const prompts = [
  // {text: "爆款分析", id: 'analysis', icon: <SearchOutlined/>},
  // {text: "爆款复刻评估", id: 'duplicateAnalysis', needProfile: true, icon: <SearchOutlined/>, quick: true},
  // {text: "秒变我的拍摄稿", id: 'changeToMyScript', needProfile: true, icon: <SearchOutlined/>, quick: true},
  // {text: "爆款逐帧分析", id: 'improveSuggestion', icon: <SearchOutlined/>, quick: true},
  { text: "extractText", id: "extractText", quick: true },
  { text: "editingTechAnalysis", id: "editingTechAnalysis", quick: true },
  { text: "effectAnalysis", id: "effectAnalysis", quick: true },
  { text: "soundAnalysis", id: "soundAnalysis", quick: true },
  { text: "coverAnalysisImages", id: "coverAnalysisImages" },
  { text: "limitAnalysisImages", id: "limitAnalysisImages" },
  { text: "limitAnalysis", id: "limitAnalysis" },
  { text: "preAnalysisImages", id: "preAnalysisImages" },
  { text: "preAnalysis", id: "preAnalysis" },
  // {text: "总结视频要点", icon: <FileTextOutlined/>},
  // {text: "关键信息提取", icon: <InfoCircleOutlined/>},
];

export const quickPrompts = prompts.filter((x) => x.quick);

// 定义数据范围选项
export const FOLLOWER_RANGES = [
  { value: "0", label: "noFollowers" },
  { value: "1-500", label: "followers1to500" },
  { value: "500-1000", label: "followers500to1k" },
  { value: "1000-5000", label: "followers1kto5k" },
  { value: "5000-10000", label: "followers5kto10k" },
  { value: "10000-50000", label: "followers10kto50k" },
  { value: "50000-100000", label: "followers50kto100k" },
  { value: "100000-500000", label: "followers100kto500k" },
  { value: "500000+", label: "followers500kPlus" },
];

export const POST_RANGES = [
  { value: "0", label: "notPublished" },
  { value: "1-5", label: "posts1to5" },
  { value: "5-10", label: "posts5to10" },
  { value: "10-50", label: "posts10to50" },
  { value: "50-200", label: "posts50to200" },
  { value: "200-500", label: "posts200to500" },
  { value: "500+", label: "posts500Plus" },
];

export const INTERACTION_RANGES = [
  { label: "0-1%", value: "0-1%", display: "interaction0to1" },
  { label: "1-3%", value: "1-3%", display: "interaction1to3" },
  { label: "3-5%", value: "3-5%", display: "interaction3to5" },
  { label: "5-10%", value: "5-10%", display: "interaction5to10" },
  { label: "10-50%", value: "10-15%", display: "interaction10to15" },
  { label: "15-20%", value: "15-20%", display: "interaction15to20" },
  { label: "20%+", value: "20%+", display: "interaction20Plus" },
];

// 域名翻译映射
export const DOMAIN_TRANSLATIONS: Record<string, string> = {
  美妆: "beauty",
  护肤: "skincare",
  基础护肤: "basicSkincare",
  功效护肤: "functionalSkincare",
  敏感肌: "sensitiveSkin",
  抗老: "antiAging",
  美白: "whitening",
  祛痘: "acneTreatment",
  彩妆: "makeup",
  底妆: "foundation",
  眼妆: "eyeMakeup",
  唇妆: "lipMakeup",
  修容: "contouring",
  眉毛: "eyebrows",
  新手妆容: "beginnerMakeup",
  美妆测评: "beautyReview",
  护肤品测评: "skincareReview",
  彩妆测评: "makeupReview",
  平价替代: "budgetAlternative",
  雷品避坑: "productWarning",
  成分解析: "ingredientAnalysis",
  医美: "medicalBeauty",
  注射类: "injection",
  激光类: "laser",
  手术类: "surgery",
  医美科普: "medicalBeautyEducation",
  术后护理: "postOpCare",
  时尚: "fashion",
  穿搭: "outfit",
  日常穿搭: "dailyOutfit",
  职场穿搭: "workOutfit",
  约会穿搭: "dateOutfit",
  旅行穿搭: "travelOutfit",
  季节穿搭: "seasonalOutfit",
  风格穿搭: "styleOutfit",
  奢侈品: "luxury",
  包包: "bags",
  首饰: "jewelry",
  腕表: "watches",
  真假辨别: "authenticityCheck",
  购买攻略: "buyingGuide",
  配饰: "accessories",
  耳饰: "earrings",
  项链: "necklaces",
  戒指: "rings",
  丝巾: "scarves",
  帽子: "hats",
  眼镜: "glasses",
  美食: "food",
  美食探店: "foodExploration",
  火锅: "hotpot",
  烧烤: "bbq",
  甜品: "desserts",
  咖啡: "coffee",
  网红店: "trendyRestaurants",
  小众店: "hiddenGems",
  烘焙: "baking",
  蛋糕: "cakes",
  面包: "bread",
  饼干: "cookies",
  挞类: "tarts",
  新手烘焙: "beginnerBaking",
  家常菜: "homeCooking",
  快手菜: "quickDishes",
  汤类: "soups",
  素食: "vegetarian",
  下饭菜: "riceCompanion",
  节日菜: "festivalDishes",
  生活: "lifestyle",
  旅行: "travel",
  母婴: "babyAndMom",
  数码: "digital",
  运动健身: "sportsAndFitness",
  教育: "education",
  娱乐: "entertainment",
  家居: "homeDecor",
  收纳: "storage",
  宠物: "pets",
  国内游: "domesticTravel",
  国外游: "internationalTravel",
  攻略: "travelGuide",
  育儿: "parenting",
  辅食: "babyFood",
  母婴用品: "babyProducts",
  手机: "mobile",
  电脑: "computer",
  摄影: "photography",
  健身: "fitness",
  瑜伽: "yoga",
  减肥: "weightLoss",
  考研: "postgraduateExam",
  外语: "foreignLanguage",
  职场技能: "careerSkills",
  搞笑: "funny",
  音乐: "music",
  影视: "movieAndTV",
  装修: "renovation",
  软装: "softDecoration",
  家具: "furniture",
  家电: "appliances",
  厨房: "kitchen",
  卧室: "bedroom",
  衣物收纳: "clothesStorage",
  厨房收纳: "kitchenStorage",
  书籍收纳: "bookStorage",
  收纳神器: "storageGadgets",
  断舍离: "minimalism",
  猫咪: "cats",
  狗狗: "dogs",
  宠物用品: "petSupplies",
  宠物训练: "petTraining",
  宠物健康: "petHealth",
  北京: "beijing",
  上海: "shanghai",
  广州: "guangzhou",
  成都: "chengdu",
  西安: "xian",
  杭州: "hangzhou",
  日本: "japan",
  韩国: "korea",
  泰国: "thailand",
  欧洲: "europe",
  美国: "usa",
  东南亚: "southeastAsia",
  签证: "visa",
  机票: "flights",
  酒店: "hotels",
  行程规划: "itineraryPlanning",
  省钱攻略: "budgetTips",
  "0-6个月": "zeroToSixMonths",
  "6-12个月": "sixToTwelveMonths",
  "1-3岁": "oneToThreeYears",
  "3-6岁": "threeToSixYears",
  育儿心得: "parentingTips",
  "6月辅食": "sixMonthFood",
  "8月辅食": "eightMonthFood",
  "12月辅食": "twelveMonthFood",
  手指食物: "fingerFood",
  营养搭配: "nutritionMix",
  奶粉: "milkPowder",
  纸尿裤: "diapers",
  玩具: "toys",
  童装: "childrenClothing",
  推车: "stroller",
  iPhone: "iphone",
  华为: "huawei",
  小米: "xiaomi",
  手机配件: "phoneAccessories",
  手机摄影: "mobilePhotography",
  笔记本: "laptop",
  台式机: "desktop",
  Mac: "mac",
  电脑配件: "computerAccessories",
  办公软件: "officeSoftware",
  相机: "camera",
  镜头: "lens",
  摄影技巧: "photographySkills",
  后期修图: "photoEditing",
  摄影器材: "photographyEquipment",
  力量训练: "strengthTraining",
  有氧运动: "cardio",
  家庭健身: "homeWorkout",
  健身装备: "fitnessEquipment",
  健身饮食: "fitnessDiet",
  基础瑜伽: "basicYoga",
  流瑜伽: "flowYoga",
  阴瑜伽: "yinYoga",
  瑜伽用品: "yogaSupplies",
  冥想: "meditation",
  减肥食谱: "dietRecipes",
  减肥运动: "weightLossExercise",
  减肥心得: "weightLossTips",
  局部减肥: "spotReduction",
  减肥产品: "weightLossProducts",
  考研英语: "graduateEnglish",
  考研数学: "graduateMath",
  考研政治: "graduatePolitics",
  专业课: "majorCourses",
  考研经验: "examExperience",
  英语学习: "englishLearning",
  日语学习: "japaneseLearning",
  韩语学习: "koreanLearning",
  口语练习: "speakingPractice",
  语言考试: "languageTest",
  Excel: "excel",
  PPT: "powerpoint",
  Word: "word",
  沟通技巧: "communicationSkills",
  时间管理: "timeManagement",
  段子: "jokes",
  沙雕视频: "funnyVideos",
  恶搞: "parody",
  模仿: "imitation",
  日常搞笑: "dailyFun",
  翻唱: "cover",
  原创: "original",
  乐器: "instruments",
  音乐分享: "musicSharing",
  音乐教学: "musicTeaching",
  电影推荐: "movieRecommendation",
  电视剧: "tvSeries",
  综艺: "variety",
  影评: "movieReview",
  演员: "actors",
};

export const getDomains = (domainKey: string) => {
  const domains = domainKey?.split("-");

  const l1 = DOMAINS.filter((x) => x.id === domains[0])?.[0];
  const l2 = l1?.subDomains?.filter(
    (x) => x.id === `${domains[0]}-${domains[1]}`
  )?.[0];
  const l3 = l2?.subDomains?.filter((x) => x.id === domainKey)?.[0];

  return [l1?.name || "", l2?.name || "", l3?.name || ""];
};

export const DOMAINS = [
  {
    id: "1",
    name: "美妆",
    subDomains: [
      {
        id: "1-1",
        name: "护肤",
        subDomains: [
          { id: "1-1-1", name: "基础护肤" },
          { id: "1-1-2", name: "功效护肤" },
          { id: "1-1-3", name: "敏感肌" },
          { id: "1-1-4", name: "抗老" },
          { id: "1-1-5", name: "美白" },
          { id: "1-1-6", name: "祛痘" },
        ],
      },
      {
        id: "1-2",
        name: "彩妆",
        subDomains: [
          { id: "1-2-1", name: "底妆" },
          { id: "1-2-2", name: "眼妆" },
          { id: "1-2-3", name: "唇妆" },
          { id: "1-2-4", name: "修容" },
          { id: "1-2-5", name: "眉毛" },
          { id: "1-2-6", name: "新手妆容" },
        ],
      },
      {
        id: "1-3",
        name: "美妆测评",
        subDomains: [
          { id: "1-3-1", name: "护肤品测评" },
          { id: "1-3-2", name: "彩妆测评" },
          { id: "1-3-3", name: "平价替代" },
          { id: "1-3-4", name: "雷品避坑" },
          { id: "1-3-5", name: "成分解析" },
        ],
      },
      {
        id: "1-4",
        name: "医美",
        subDomains: [
          { id: "1-4-1", name: "注射类" },
          { id: "1-4-2", name: "激光类" },
          { id: "1-4-3", name: "手术类" },
          { id: "1-4-4", name: "医美科普" },
          { id: "1-4-5", name: "术后护理" },
        ],
      },
    ],
  },
  {
    id: "2",
    name: "时尚",
    subDomains: [
      {
        id: "2-1",
        name: "穿搭",
        subDomains: [
          { id: "2-1-1", name: "日常穿搭" },
          { id: "2-1-2", name: "职场穿搭" },
          { id: "2-1-3", name: "约会穿搭" },
          { id: "2-1-4", name: "旅行穿搭" },
          { id: "2-1-5", name: "季节穿搭" },
          { id: "2-1-6", name: "风格穿搭" },
        ],
      },
      {
        id: "2-2",
        name: "奢侈品",
        subDomains: [
          { id: "2-2-1", name: "包包" },
          { id: "2-2-2", name: "首饰" },
          { id: "2-2-3", name: "腕表" },
          { id: "2-2-4", name: "真假辨别" },
          { id: "2-2-5", name: "购买攻略" },
        ],
      },
      {
        id: "2-3",
        name: "配饰",
        subDomains: [
          { id: "2-3-1", name: "耳饰" },
          { id: "2-3-2", name: "项链" },
          { id: "2-3-3", name: "戒指" },
          { id: "2-3-4", name: "丝巾" },
          { id: "2-3-5", name: "帽子" },
          { id: "2-3-6", name: "眼镜" },
        ],
      },
    ],
  },
  {
    id: "3",
    name: "美食",
    subDomains: [
      {
        id: "3-1",
        name: "美食探店",
        subDomains: [
          { id: "3-1-1", name: "火锅" },
          { id: "3-1-2", name: "烧烤" },
          { id: "3-1-3", name: "甜品" },
          { id: "3-1-4", name: "咖啡" },
          { id: "3-1-5", name: "网红店" },
          { id: "3-1-6", name: "小众店" },
        ],
      },
      {
        id: "3-2",
        name: "烘焙",
        subDomains: [
          { id: "3-2-1", name: "蛋糕" },
          { id: "3-2-2", name: "面包" },
          { id: "3-2-3", name: "饼干" },
          { id: "3-2-4", name: "挞类" },
          { id: "3-2-5", name: "新手烘焙" },
        ],
      },
      {
        id: "3-3",
        name: "家常菜",
        subDomains: [
          { id: "3-3-1", name: "快手菜" },
          { id: "3-3-2", name: "汤类" },
          { id: "3-3-3", name: "素食" },
          { id: "3-3-4", name: "下饭菜" },
          { id: "3-3-5", name: "节日菜" },
        ],
      },
    ],
  },
  {
    id: "4",
    name: "生活",
    subDomains: [
      {
        id: "4-1",
        name: "家居",
        subDomains: [
          { id: "4-1-1", name: "装修" },
          { id: "4-1-2", name: "软装" },
          { id: "4-1-3", name: "家具" },
          { id: "4-1-4", name: "家电" },
          { id: "4-1-5", name: "厨房" },
          { id: "4-1-6", name: "卧室" },
        ],
      },
      {
        id: "4-2",
        name: "收纳",
        subDomains: [
          { id: "4-2-1", name: "衣物收纳" },
          { id: "4-2-2", name: "厨房收纳" },
          { id: "4-2-3", name: "书籍收纳" },
          { id: "4-2-4", name: "收纳神器" },
          { id: "4-2-5", name: "断舍离" },
        ],
      },
      {
        id: "4-3",
        name: "宠物",
        subDomains: [
          { id: "4-3-1", name: "猫咪" },
          { id: "4-3-2", name: "狗狗" },
          { id: "4-3-3", name: "宠物用品" },
          { id: "4-3-4", name: "宠物训练" },
          { id: "4-3-5", name: "宠物健康" },
        ],
      },
    ],
  },
  {
    id: "5",
    name: "旅行",
    subDomains: [
      {
        id: "5-1",
        name: "国内游",
        subDomains: [
          { id: "5-1-1", name: "北京" },
          { id: "5-1-2", name: "上海" },
          { id: "5-1-3", name: "广州" },
          { id: "5-1-4", name: "成都" },
          { id: "5-1-5", name: "西安" },
          { id: "5-1-6", name: "杭州" },
        ],
      },
      {
        id: "5-2",
        name: "国外游",
        subDomains: [
          { id: "5-2-1", name: "日本" },
          { id: "5-2-2", name: "韩国" },
          { id: "5-2-3", name: "泰国" },
          { id: "5-2-4", name: "欧洲" },
          { id: "5-2-5", name: "美国" },
          { id: "5-2-6", name: "东南亚" },
        ],
      },
      {
        id: "5-3",
        name: "攻略",
        subDomains: [
          { id: "5-3-1", name: "签证" },
          { id: "5-3-2", name: "机票" },
          { id: "5-3-3", name: "酒店" },
          { id: "5-3-4", name: "行程规划" },
          { id: "5-3-5", name: "省钱攻略" },
        ],
      },
    ],
  },
  {
    id: "6",
    name: "母婴",
    subDomains: [
      {
        id: "6-1",
        name: "育儿",
        subDomains: [
          { id: "6-1-1", name: "0-6个月" },
          { id: "6-1-2", name: "6-12个月" },
          { id: "6-1-3", name: "1-3岁" },
          { id: "6-1-4", name: "3-6岁" },
          { id: "6-1-5", name: "育儿心得" },
        ],
      },
      {
        id: "6-2",
        name: "辅食",
        subDomains: [
          { id: "6-2-1", name: "6月辅食" },
          { id: "6-2-2", name: "8月辅食" },
          { id: "6-2-3", name: "12月辅食" },
          { id: "6-2-4", name: "手指食物" },
          { id: "6-2-5", name: "营养搭配" },
        ],
      },
      {
        id: "6-3",
        name: "母婴用品",
        subDomains: [
          { id: "6-3-1", name: "奶粉" },
          { id: "6-3-2", name: "纸尿裤" },
          { id: "6-3-3", name: "玩具" },
          { id: "6-3-4", name: "童装" },
          { id: "6-3-5", name: "推车" },
        ],
      },
    ],
  },
  {
    id: "7",
    name: "数码",
    subDomains: [
      {
        id: "7-1",
        name: "手机",
        subDomains: [
          { id: "7-1-1", name: "iPhone" },
          { id: "7-1-2", name: "华为" },
          { id: "7-1-3", name: "小米" },
          { id: "7-1-4", name: "手机配件" },
          { id: "7-1-5", name: "手机摄影" },
        ],
      },
      {
        id: "7-2",
        name: "电脑",
        subDomains: [
          { id: "7-2-1", name: "笔记本" },
          { id: "7-2-2", name: "台式机" },
          { id: "7-2-3", name: "Mac" },
          { id: "7-2-4", name: "电脑配件" },
          { id: "7-2-5", name: "办公软件" },
        ],
      },
      {
        id: "7-3",
        name: "摄影",
        subDomains: [
          { id: "7-3-1", name: "相机" },
          { id: "7-3-2", name: "镜头" },
          { id: "7-3-3", name: "摄影技巧" },
          { id: "7-3-4", name: "后期修图" },
          { id: "7-3-5", name: "摄影器材" },
        ],
      },
    ],
  },
  {
    id: "8",
    name: "运动健身",
    subDomains: [
      {
        id: "8-1",
        name: "健身",
        subDomains: [
          { id: "8-1-1", name: "力量训练" },
          { id: "8-1-2", name: "有氧运动" },
          { id: "8-1-3", name: "家庭健身" },
          { id: "8-1-4", name: "健身装备" },
          { id: "8-1-5", name: "健身饮食" },
        ],
      },
      {
        id: "8-2",
        name: "瑜伽",
        subDomains: [
          { id: "8-2-1", name: "基础瑜伽" },
          { id: "8-2-2", name: "流瑜伽" },
          { id: "8-2-3", name: "阴瑜伽" },
          { id: "8-2-4", name: "瑜伽用品" },
          { id: "8-2-5", name: "冥想" },
        ],
      },
      {
        id: "8-3",
        name: "减肥",
        subDomains: [
          { id: "8-3-1", name: "减肥食谱" },
          { id: "8-3-2", name: "减肥运动" },
          { id: "8-3-3", name: "减肥心得" },
          { id: "8-3-4", name: "局部减肥" },
          { id: "8-3-5", name: "减肥产品" },
        ],
      },
    ],
  },
  {
    id: "9",
    name: "教育",
    subDomains: [
      {
        id: "9-1",
        name: "考研",
        subDomains: [
          { id: "9-1-1", name: "考研英语" },
          { id: "9-1-2", name: "考研数学" },
          { id: "9-1-3", name: "考研政治" },
          { id: "9-1-4", name: "专业课" },
          { id: "9-1-5", name: "考研经验" },
        ],
      },
      {
        id: "9-2",
        name: "外语",
        subDomains: [
          { id: "9-2-1", name: "英语学习" },
          { id: "9-2-2", name: "日语学习" },
          { id: "9-2-3", name: "韩语学习" },
          { id: "9-2-4", name: "口语练习" },
          { id: "9-2-5", name: "语言考试" },
        ],
      },
      {
        id: "9-3",
        name: "职场技能",
        subDomains: [
          { id: "9-3-1", name: "Excel" },
          { id: "9-3-2", name: "PPT" },
          { id: "9-3-3", name: "Word" },
          { id: "9-3-4", name: "沟通技巧" },
          { id: "9-3-5", name: "时间管理" },
        ],
      },
    ],
  },
  {
    id: "10",
    name: "娱乐",
    subDomains: [
      {
        id: "10-1",
        name: "搞笑",
        subDomains: [
          { id: "10-1-1", name: "段子" },
          { id: "10-1-2", name: "沙雕视频" },
          { id: "10-1-3", name: "恶搞" },
          { id: "10-1-4", name: "模仿" },
          { id: "10-1-5", name: "日常搞笑" },
        ],
      },
      {
        id: "10-2",
        name: "音乐",
        subDomains: [
          { id: "10-2-1", name: "翻唱" },
          { id: "10-2-2", name: "原创" },
          { id: "10-2-3", name: "乐器" },
          { id: "10-2-4", name: "音乐分享" },
          { id: "10-2-5", name: "音乐教学" },
        ],
      },
      {
        id: "10-3",
        name: "影视",
        subDomains: [
          { id: "10-3-1", name: "电影推荐" },
          { id: "10-3-2", name: "电视剧" },
          { id: "10-3-3", name: "综艺" },
          { id: "10-3-4", name: "影评" },
          { id: "10-3-5", name: "演员" },
        ],
      },
    ],
  },
];

// 获取翻译后的域名
export const getTranslatedDomains = (
  domainKey: string,
  t: (key: string) => string
) => {
  const domains = getDomains(domainKey);
  return domains.map((domain) =>
    domain ? t(DOMAIN_TRANSLATIONS[domain] || domain) : ""
  );
};
