export const CATEGORIES = [
    {id: "", name: "全部", label: "all"},
    {id: "finance", name: "财经", label: "finance"},
    {id: "ai", name: "AI", label: "ai"},
    {id: "health", name: "大健康", label: "health"},
    {id: "workplace", name: "职场", label: "workplace"},
    {id: "emotion", name: "情感", label: "emotion"},
    {id: "tech", name: "科技数码", label: "tech"},
    {id: "home", name: "家居", label: "home"},
    {id: "food", name: "美食", label: "food"},
    {id: "parenting", name: "母婴育儿", label: "parenting"},
    {id: "skincare", name: "医美护肤", label: "skincare"},
    {id: "jewelry", name: "珠宝", label: "jewelry"},
    {id: "studyabroad", name: "移民留学", label: "studyabroad"},
    {id: "insurance", name: "财富保险", label: "insurance"},
    {id: "realestate", name: "房地产", label: "realestate"},
    {id: "trip", name: "旅行", label: "trip"},
    {id: "personalIp", label: "personalIp"},
    {id: "outfits", label: "outfits"},
    {id: "fitness", label: "fitness"},
    {id: "game", label: "game"},
    {id: "car", label: "car"},
    {id: "diy", label: "diy"},
    {id: "ecommerce", label: "ecommerce"},
    {id: "pet", label: "pet"},
    {id: "movie", label: "movie", name: "影视"},
    {id: "drawing", label: "drawing", name: "绘画"},
    {id: "science", label: "science", name: "科学科普"},
    {id: "psychology", label: "psychology", name: "心理"},
    {id: "reading", label: "reading", name: "读书"},
    {id: "music", label: "music", name: "音乐"},
    {id: "outdoors", label: "outdoors", name: "户外"},
    {id: "camping", label: "camping", name: "露营"},
    {id: "sports", label: "sports", name: "体育"},
    {id: "mensgrooming", label: "mensgrooming", name: "男士理容"},
    {id: "learning", label: "learning", name: "学习"},
    {id: "culture", label: "culture", name: "文化"},
    {id: "photography", label: "photography", name: "摄影"},
    {id: "wedding", label: "wedding", name: "婚礼"},
    {id: "motor", label: "motor", name: "机车"},
    {id: "cartoon", label: "cartoon", name: "动漫"},
    {id: "planner", label: "planner", name: "文具手帐"},
];
